### ISSUE TITLE
有考虑支持asp.net core吗？

### ISSUE THREAD

**Issue by qcjxberin** [iboxdb/ftserver-cs#1]
有考虑支持asp.net core吗？

**Comment by iboxdb** [comment]
理论上把 iBoxDB.NET2.dll 换为 [iBoxDB.DLL](https://www.nuget.org/packages/iBoxDB/) ， 然后把aspx的代码换个位置就能在asp.net core上运行。

**Comment by qcjxberin** [comment]
直接调用不行的。是要core版本，不是framework版本的。

**Comment by qcjxberin** [comment]
如果能支持的话，我想用到我的新项目里。

**Comment by iboxdb** [comment]
在很早期的 .net core 下测试过， https://github.com/iboxdb/aspnet-cross-platform-db ,   可能要更换一下 CsQuery 这个包，这个包主要是发送 HTTP.GET,  兼容不会有大问题，主要是现在asp.net core 配置环境不多，而asp.net基本每个.net机都支持。
这个项目的代码就是在Linux下开发的。

**Comment by qcjxberin** [comment]
现在基本上很多新的项目都已经在使用.net core了。除非是旧有的一些技术暂时不能被支持到core上才会用原有的。建议能够做一个core版本的，目前来说core已经算是比较完善了。

**Comment by qcjxberin** [comment]
现在真正做项目的都是自己服务器，不会说还去买虚拟主机来使用。
