### ISSUE TITLE
有没有可能增加site：指令来只调用指定域名的数据

### ISSUE THREAD

**Issue by qcjxberin** [iboxdb/ftserver-cs#10]
有没有可能增加site：指令来只调用指定域名的数据

**Comment by iboxdb** [comment]
应该在搜索位置直接写域名就可以  【周伯通 未受伤  localhost】，建索引时已经把域名加入。

https://github.com/iboxdb/ftserver-cs/blob/600761dd64fb3855f9d073add2d9a09eb26257a4/FTServer/Code/IndexFields.cs#L85
