### ISSUE TITLE
结果能不能去重的？

### ISSUE THREAD

**Issue by qcjxberin** [iboxdb/ftserver-cs#5]
![image](https://user-images.githubusercontent.com/5792218/83330061-6da1e080-a2bf-11ea-9b71-cbd928333069.png)
前面两个都是一样的链接

**Comment by iboxdb** [comment]
这两个连接的颜色不一样，是不同优先级，这是因为数据量少，再多加几条，数据量大时就自动分开了.

**Comment by qcjxberin** [comment]
好的。有没有手动添加索引的教程的？

**Comment by qcjxberin** [comment]
比如我想做站内搜索具体关联某个表某个ID的？

**Comment by iboxdb** [comment]
参考调用这个类的方法
Code/FTSEngine.cs
 Engine.indexText(IBox box, long id, String text, bool isRemove)
定义自己的 id 与 text

**Comment by iboxdb** [comment]
EngineConsole/EngineTest.cs 里的
FTServer.EngineTest.test_main()
方法是快捷入门，就是有多种文字哪个方法，Search再结合 IndexAPI.Search()

**Comment by qcjxberin** [comment]
分词索引是自动的吗？

**Comment by iboxdb** [comment]
中文，日文不分词，按位置搜索，不按词搜索。大概如下

查  “好的”， 通过 “好“，得到位置 9 ， 然后查 ”的“字， 带一个条件， where 位置=9+1 ，

**Comment by qcjxberin** [comment]
可以同时查多个搜索词吗？

**Comment by iboxdb** [comment]
精确搜索多语多词， 直接试【 m6313 高性 】搜索一下

**Comment by qcjxberin** [comment]
好的，感谢，我先试一下。

**Comment by iboxdb** [comment]
当前韩语是按中文方式处理字，如果按更快的英文方式处理，修改
StringUtil.isWord（） 在里面加入对应字符集.

**Comment by qcjxberin** [comment]
可以关联某个表吗？比如我多个表，如果只是id的话，没法返回关联表和对应的链接

**Comment by iboxdb** [comment]
id 可以自己定义的，long 63 位可用，
每个表定义一个 数字，如
Table1 = 1, 
然后 Table1 的  id 左移两位， 再加入 Table1, 读时右移回就行了

**Comment by qcjxberin** [comment]
好的，感谢

**Comment by iboxdb** [comment]
先转为 long 再运行，使用 int 会溢出

**Comment by qcjxberin** [comment]
OK

**Comment by qcjxberin** [comment]
可以同时写入多个字段的数据内容吧？是直接把多个字段的内容放在一起，还是要分开写的？

**Comment by iboxdb** [comment]
根据自己需要设置，大部分应该是合并， 如购物网站， 会自己加文字，如
Text + " 轻便快捷 " + ”  高清 “， 关键是读回时， 长度超过 Text.Length 就跳过。

如果需要分开，就把 id 再左移两位。

另外  EngineConsole/ObjectSearch.cs 有自己生成描述文本的例子。

**Comment by qcjxberin** [comment]
长度超过 Text.Length 就跳过  那这个长度是有限制的吗？

**Comment by iboxdb** [comment]
长度没限制，我一般使用 10000 做测试.

**Comment by qcjxberin** [comment]
好
