### ISSUE TITLE
能支持多少数据量的？

### ISSUE THREAD

**Issue by qcjxberin** [iboxdb/ftserver-cs#6]
能支持多少数据量的？怎么样调整搜索结果的权重的？

**Comment by iboxdb** [comment]
1.多少数据量
下载新版本试试，测试数据库文件5G时，搜索速度没多大变化，只在重启后新建索引时会比较慢，缓存生成后，速度就恢复了。

2.调整搜索结果的权重
再建一次索引，使用新的权重id。原索引可以先删除掉。但对于同一个网页，不要使用一个线程删除，一个线程新建，要按顺序，先删后建。不同页面没限制，但因为不能确定最终用户的操作，所以最好加一个锁。

如果你知道极限多少告诉我。

**Comment by iboxdb** [comment]
2. ...
如果不是对整个页面调整权重，只对部分关键内容调整权重，调用 

```cs
void addPageCustomText(String url, String title, String content)｛
   text.priority = PageText.userPriority;
   ...
｝
```

这个方法, priority 每次增加一。
