### ISSUE TITLE
要是有更大数据量支撑的方案就最好了。

### ISSUE THREAD

**Issue by qcjxberin** [iboxdb/ftserver-cs#7]
要是有更大数据量支撑的方案就最好了。

**Comment by qcjxberin** [comment]
另外能不能限制只能采集指定域名的，不要让采集器到处乱跑

**Comment by iboxdb** [comment]
//更大数据量支撑的方案
安装到几台机器上，使用Nginx转发请求，搜索服务每次返回不同结果效果更好。
//采集指定域名
https://github.com/iboxdb/ftserver-cs/blob/4bc5fafe9cfd605d8478c7bbf9420dcbf9bc1a83/FTServer/Code/Html.cs#L130
可以这里设置域名。

**Comment by qcjxberin** [comment]
//更大数据量支撑的方案
安装到几台机器上，使用Nginx转发请求，搜索服务每次返回不同结果效果更好。


关于Nginx转发请求，这个能不能大概讲解下具体的操作步骤的。还没有怎么玩过这种
