### ISSUE TITLE
目前怎么输入网址出现下面的图片的。

### ISSUE THREAD

**Issue by qcjxberin** [iboxdb/ftserver-cs#8]
![image](https://user-images.githubusercontent.com/5792218/111867525-88108c00-89af-11eb-934f-5141f719f357.png)

**Comment by iboxdb** [comment]
建索引修改为在后台执行，这是给高级用户录入数据的页面，提示查看控制台的输出，对普通用户这页面有点奇怪，但普通用户只去查数据，不去录入数据，可根据实际应用美化操作效果。
