### ISSUE TITLE
分词工具是什么

### ISSUE THREAD

**Issue by guxing2** [iboxdb/ftserver-cs#9]
如题,项目里面使用什么分词工具?

**Comment by iboxdb** [comment]
没使用分词工具。可以搜索一个单字。
在 and 条件转换 or 条件哪段可以考虑使用分词，但不要使用太重的分词工具。

https://github.com/iboxdb/ftserver-cs/blob/4bc5fafe9cfd605d8478c7bbf9420dcbf9bc1a83/FTServer/Code/IndexAPI.cs#L42
